name: Code quality report deploy
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up
        shell: bash
        run: |
          git clone https://github.com/WebFrame/Core.git
          cd Core
          git checkout v2
          cd ..
      - name: Deploy cppcheck report
        shell: bash
        run: |
          mkdir v2
          cp -rf Core/cppcheck_report v2/
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add v2/
          git commit -m "Add changes" -a
      - name: Push static code analysis
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
